#!/usr/bin/bash env
#This script replace a line with multiple lines

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i "/listen 80 default_server;/a \ \ \ \ rewrite ^/redirect_me https://twitter.com/duke_ibadan permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
