#!/usr/bin/env bash
# This script configures Nginx so that its HTTP response contains a custom header on web-01 and web-02

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

sudo chmod -R 755 /var/www

# This creates the index page
echo 'Hello World!' |sudo tee  /var/www/html/index.html

# This creates a webpage for error 404
echo "Error, go back" |sudo tee /var/www/html/404.html

# This configure redirect for a single page and display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.bide.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code for error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# This restarts the web server 
sudo service nginx restart
