#!/usr/bin/env bash
# This script install and configure HAProxy on lb-01 server
# Configure HAProxy so it can send traffic to web-01 and web-02 servers
# This installs & configures HAproxy on  lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# This edit the config file
server_config=\
"
frontend  my-frontend
        bind *:80
        mode http
        default_backend my-backend
backend my-backend
        balance roundrobin
        server 63210-web-01 100.25.19.204:80 check
        server 63210-web-02 54.157.159.85:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
