#!/usr/bin/env bash
# This script install and configure HAProxy on lb-01 server
# Configure HAProxy so it can send traffic to web-01 and web-02 servers
# This installs & configures HAproxy on  lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# This edit the config file
server_config=\
"
frontend  my-frontend
        bind    
