#!/usr/bin/env bash
#This Bash script pings an IP address passed as an argument

# Check if an argument is passed
if [ $# -eq 0 ];
then
	echo "Usage: $0 {IP_ADDRESS}"
	exit 1
fi

ip_address=$1

ping -c 5 "$ip_address"
