#!/usr/bin/env bash
#A bash scrip that displays 'Best School' 10 times except the 9th iteration.

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]; then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	counter=$((counter + 1))
done
