#!/usr/bin/env bash
#A bash script that loops from 1 - 10 and displays a text

count=1
while [ $count -lt 11 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
