#!/usr/bin/env bash
#A Bash script that displays the content of the current directory

for item in *;
	do  # Check if the item is a regular file or a directory (not a hidden file)
		if [ -f "$item" ] || [ -d "$item" ];
		then
		name=$(echo "$item" | cut -d'-' -f2-)
	echo "$name"
	fi
done
