#!/usr/bin/env bash
#A Bash script that configures an Ubuntu server.

if [ "$(id -u)" -ne 0 ];
then
	echo "This script must be run with root privileges. Please use sudo or run as root."
	exit 1
fi

echo "127.0.0.2    localhost" >> /etc/hosts
echo "8.8.8.8      facebook.com" >> /etc/hosts

echo "Configuration completed. Localhost is now set to 127.0.0.2 and facebook.com resolves to 8.8.8.8."
