#!/usr/bin/env bash
#A Bash script that displays all active IPv4 IPs on the machine it’s executed on

interfaces=$(ip -4 addr show | awk '/inet/ {print $2}')

while read -r interface;
do
	echo "${interface%%/*}"
done <<< "$interfaces"
