#!/usr/bin/env bash
#A Bash script that listens on port 98 on localhost

if [ "$(id -u)" -ne 0 ];
then
	echo "This script must be run with root privileges. Please use sudo or run as root."
	exit 1
fi

nc -l 127.0.0.1 98
